<template>
  <section id="Rarity" class="mondrian-border-bottom">
    <div
      class="container max-w-4xl mx-auto px-8 grid md:grid-cols-2 gap-4 md:gap-20 items-center"
    >
      <div class="space-y-4">
        <div class="font-bold text-5xl relative z-10 gs_reveal">
          Rarity
          <span
            class="text-blueish text-[2.5rem] font-normal tracking-[0.13em] font-serif absolute -left-4 top-0 -z-10"
            >Rarity</span
          >
        </div>
        <p class="gs_reveal">
          Each NFT is algorithmically generated by combining 20+ unique traits
          across different categories. There are only 13 legendary NFTs
          available for grabs.
        </p>
        <ul>
          <li
            class="gs_reveal p-2 flex justify-between w-full border-8 border-black border-t-0"
            :class="[index === 0 && 'border-t-8', rarity.classes]"
            v-for="(rarity, index) in rarities"
            :key="rarity.type"
          >
            <span class="font-bold">{{ rarity.type }}</span>
            <span>{{ rarity.trait }}</span>
          </li>
        </ul>
      </div>
      <img
        src="@/assets/images/image-4.png"
        alt="Rarity"
        class="gs_reveal gs_reveal_fromRight"
      />
    </div>
  </section>
</template>

<script setup lang="ts">
import useTransition from "@/composables/useTransition";
useTransition();

const rarities = [
  {
    type: "Common",
    trait: "Plain",
    classes: "bg-[rgba(228,14,22,0.04)]",
  },
  {
    type: "Uncommon",
    trait: "Simple",
    classes: "bg-[rgba(228,14,22,0.25)]",
  },
  {
    type: "Rare",
    trait: "Creative",
    classes: "bg-[rgba(228,14,22,0.5)]",
  },
  {
    type: "Ultra",
    trait: "Expressive",
    classes: "bg-[rgba(228,14,22,0.75)]",
  },
  {
    type: "Legendary",
    trait: "Supervision",
    classes: "bg-[rgba(228,14,22,1)]",
  },
];
</script>
