<template>
  <section id="Rarity" class="mondrian-border-b">
    <div
      class="container grid items-center max-w-4xl gap-4 px-8 mx-auto md:grid-cols-2 md:gap-20"
    >
      <div class="space-y-4">
        <h2 class="section-title" v-animate>Rarity</h2>

        <p v-animate>
          Each NFT is algorithmically generated by combining 20+ unique traits
          across different categories. There are only 13 legendary NFTs
          available for grabs.
        </p>
        <ul>
          <li
            class="flex justify-between w-full p-2 border-4 border-t-0 border-black"
            v-animate
            :class="[
              index === 0 && 'border-t-4 rounded-t-xl',
              index === rarities.length - 1 && 'rounded-b-xl',
              rarity.classes,
            ]"
            v-for="(rarity, index) in rarities"
            :key="rarity.type"
          >
            <span class="font-semibold">{{ rarity.type }}</span>
            <span class="">{{ rarity.trait }}</span>
          </li>
        </ul>
      </div>
      <img src="@/assets/images/image-4.png" alt="Rarity" v-animate />
    </div>
  </section>
</template>

<script setup lang="ts">
const rarities = [
  {
    type: "Common",
    trait: "Plain",
    classes: "bg-[rgba(228,14,22,0.04)]",
  },
  {
    type: "Uncommon",
    trait: "Simple",
    classes: "bg-[rgba(228,14,22,0.25)]",
  },
  {
    type: "Rare",
    trait: "Creative",
    classes: "bg-[rgba(228,14,22,0.5)]",
  },
  {
    type: "Ultra",
    trait: "Expressive",
    classes: "bg-[rgba(228,14,22,0.75)]",
  },
  {
    type: "Legendary",
    trait: "Supervision",
    classes: "bg-[rgba(228,14,22,1)]",
  },
];
</script>
