name: Deployment

# Controls when the action will run.
on:
  # manual trigger a new image build for dockerhub 
  workflow_dispatch

jobs:
  push:
    name: Push to Docker Hub
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # build docker image and push to docker hub
    steps:
      - name: checkout repo
        uses: actions/checkout@v3.0.0

      - name: set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/whitelabel-backend:latest

  copy:
    name: Copy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy config to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        source: "config.js"
        target: "/opt/mondrians/"
        tar_tmp_path: "/home/amrap030/tmp"
        overwrite: true
  
  start:
    name: Start Containers
    runs-on: ubuntu-latest
    needs: [push, copy]
    steps:
      - name: Start docker containers
        uses: appleboy/ssh-action@v0.1.4
        env:
          IMAGE_NAME: "amrap030/whitelabel-backend"
          CONTAINER_NAME: "whitelabel-backend"
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          envs: IMAGE_NAME,CONTAINER_NAME
          script: |
            cd /opt/mondrians
            docker-compose down
            docker rmi $IMAGE_NAME
            docker-compose up -d